leftnav:
- identifier: 27336534-d1bb-b968-4f13-94e394585355
  name: Instructor Insights
  url: /pages/instructor-insights
  weight: 10
- identifier: external-7d8e42c5f7d04aa2803d063cec728e0f
  name: Online Publication
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+0.501x+2T2019/about
  weight: 1000
